.Id SCCS-info %W% %E% 
.Id $Id: pbmshift.man,v 1.4 1995/01/05 19:52:26 sander Exp $
.TH PBMSHIFT 1l 1995/01/05 "Release 1.3" 
.SH NAME
pbmshift \- shift a PBM-P4-file to the right lower corner 
.SH SYNOPSIS
.B pbmshift 
infile topmargin leftmargin outfile 
.SH DESCRIPTION
.I Pbmshift 
reads a PBM file in P4 format and produces a new PBM file in P4 format.
The output is shifted to the right by
.I leftmargin
pixels
and to the lower by
.I topmargin
pixels. 
This tool can be used to modify the image produced as
export output of the 
.I VCG tool 
from a graph before printing it on paper.
In this way, margins can be produced to position the image on
the paper.
Negative margins are allowed.
.SH WARNING
This utility does not work with the PBM-P1-format !!! 
It is not a general conversion utility but only a small demonstation
how to deal with the output of the
.I VCG tool. 
There are excellent standard utilities for PBM-Files by Jef Poskanzer
.I (pnmmargin)
but
.I pbmshift
should be much faster on large files.
.SH SEE ALSO
vcg(l) pnmmargin(l) pbmrot90(l) pbm2hp(l)
.SH BUGS
Currently, no bugs are known.
.SH ACKNOWLEDGEMENT
Jef Poskanzer is the initiator and main implementor of
the PBM package that contains various image processing
routines and printer drivers.
.SH AUTHOR
Georg Sander, University of Saarland.

